/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AlbumRouteImport } from './routes/album'
import { Route as AlbumEventRouteImport } from './routes/album-event'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as CameraRouteImport } from './routes/camera'
import { Route as ChallengeDetailRouteImport } from './routes/challenge-detail'
import { Route as ChallengesRouteImport } from './routes/challenges'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as JoinRouteImport } from './routes/join'
import { Route as LobbyRouteImport } from './routes/lobby'
import { Route as NightRecapRouteImport } from './routes/night-recap'
import { Route as NotificationsRouteImport } from './routes/notifications'
import { Route as PartyRouteImport } from './routes/party'
import { Route as ProfileRouteImport } from './routes/profile'
import { Route as RecapRouteImport } from './routes/recap'
import { Route as SabotageRouteImport } from './routes/sabotage'
import { Route as ScanRouteImport } from './routes/scan'
import { Route as SettingsRouteImport } from './routes/settings'
import { Route as ShopRouteImport } from './routes/shop'
import { Route as VotingRouteImport } from './routes/voting'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AlbumRoute = AlbumRouteImport.update({
  id: '/album',
  path: '/album',
  getParentRoute: () => rootRouteImport,
} as any)
const AlbumEventRoute = AlbumEventRouteImport.update({
  id: '/album-event',
  path: '/album-event',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const CameraRoute = CameraRouteImport.update({
  id: '/camera',
  path: '/camera',
  getParentRoute: () => rootRouteImport,
} as any)
const ChallengeDetailRoute = ChallengeDetailRouteImport.update({
  id: '/challenge-detail',
  path: '/challenge-detail',
  getParentRoute: () => rootRouteImport,
} as any)
const ChallengesRoute = ChallengesRouteImport.update({
  id: '/challenges',
  path: '/challenges',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const JoinRoute = JoinRouteImport.update({
  id: '/join',
  path: '/join',
  getParentRoute: () => rootRouteImport,
} as any)
const LobbyRoute = LobbyRouteImport.update({
  id: '/lobby',
  path: '/lobby',
  getParentRoute: () => rootRouteImport,
} as any)
const NightRecapRoute = NightRecapRouteImport.update({
  id: '/night-recap',
  path: '/night-recap',
  getParentRoute: () => rootRouteImport,
} as any)
const NotificationsRoute = NotificationsRouteImport.update({
  id: '/notifications',
  path: '/notifications',
  getParentRoute: () => rootRouteImport,
} as any)
const PartyRoute = PartyRouteImport.update({
  id: '/party',
  path: '/party',
  getParentRoute: () => rootRouteImport,
} as any)
const ProfileRoute = ProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => rootRouteImport,
} as any)
const RecapRoute = RecapRouteImport.update({
  id: '/recap',
  path: '/recap',
  getParentRoute: () => rootRouteImport,
} as any)
const SabotageRoute = SabotageRouteImport.update({
  id: '/sabotage',
  path: '/sabotage',
  getParentRoute: () => rootRouteImport,
} as any)
const ScanRoute = ScanRouteImport.update({
  id: '/scan',
  path: '/scan',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const ShopRoute = ShopRouteImport.update({
  id: '/shop',
  path: '/shop',
  getParentRoute: () => rootRouteImport,
} as any)
const VotingRoute = VotingRouteImport.update({
  id: '/voting',
  path: '/voting',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/album': typeof AlbumRoute
  '/album-event': typeof AlbumEventRoute
  '/auth': typeof AuthRoute
  '/camera': typeof CameraRoute
  '/challenge-detail': typeof ChallengeDetailRoute
  '/challenges': typeof ChallengesRoute
  '/dashboard': typeof DashboardRoute
  '/join': typeof JoinRoute
  '/lobby': typeof LobbyRoute
  '/night-recap': typeof NightRecapRoute
  '/notifications': typeof NotificationsRoute
  '/party': typeof PartyRoute
  '/profile': typeof ProfileRoute
  '/recap': typeof RecapRoute
  '/sabotage': typeof SabotageRoute
  '/scan': typeof ScanRoute
  '/settings': typeof SettingsRoute
  '/shop': typeof ShopRoute
  '/voting': typeof VotingRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/album': typeof AlbumRoute
  '/album-event': typeof AlbumEventRoute
  '/auth': typeof AuthRoute
  '/camera': typeof CameraRoute
  '/challenge-detail': typeof ChallengeDetailRoute
  '/challenges': typeof ChallengesRoute
  '/dashboard': typeof DashboardRoute
  '/join': typeof JoinRoute
  '/lobby': typeof LobbyRoute
  '/night-recap': typeof NightRecapRoute
  '/notifications': typeof NotificationsRoute
  '/party': typeof PartyRoute
  '/profile': typeof ProfileRoute
  '/recap': typeof RecapRoute
  '/sabotage': typeof SabotageRoute
  '/scan': typeof ScanRoute
  '/settings': typeof SettingsRoute
  '/shop': typeof ShopRoute
  '/voting': typeof VotingRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/album': typeof AlbumRoute
  '/album-event': typeof AlbumEventRoute
  '/auth': typeof AuthRoute
  '/camera': typeof CameraRoute
  '/challenge-detail': typeof ChallengeDetailRoute
  '/challenges': typeof ChallengesRoute
  '/dashboard': typeof DashboardRoute
  '/join': typeof JoinRoute
  '/lobby': typeof LobbyRoute
  '/night-recap': typeof NightRecapRoute
  '/notifications': typeof NotificationsRoute
  '/party': typeof PartyRoute
  '/profile': typeof ProfileRoute
  '/recap': typeof RecapRoute
  '/sabotage': typeof SabotageRoute
  '/scan': typeof ScanRoute
  '/settings': typeof SettingsRoute
  '/shop': typeof ShopRoute
  '/voting': typeof VotingRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/album'
    | '/album-event'
    | '/auth'
    | '/camera'
    | '/challenge-detail'
    | '/challenges'
    | '/dashboard'
    | '/join'
    | '/lobby'
    | '/night-recap'
    | '/notifications'
    | '/party'
    | '/profile'
    | '/recap'
    | '/sabotage'
    | '/scan'
    | '/settings'
    | '/shop'
    | '/voting'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/album'
    | '/album-event'
    | '/auth'
    | '/camera'
    | '/challenge-detail'
    | '/challenges'
    | '/dashboard'
    | '/join'
    | '/lobby'
    | '/night-recap'
    | '/notifications'
    | '/party'
    | '/profile'
    | '/recap'
    | '/sabotage'
    | '/scan'
    | '/settings'
    | '/shop'
    | '/voting'
  id:
    | '__root__'
    | '/'
    | '/album'
    | '/album-event'
    | '/auth'
    | '/camera'
    | '/challenge-detail'
    | '/challenges'
    | '/dashboard'
    | '/join'
    | '/lobby'
    | '/night-recap'
    | '/notifications'
    | '/party'
    | '/profile'
    | '/recap'
    | '/sabotage'
    | '/scan'
    | '/settings'
    | '/shop'
    | '/voting'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AlbumRoute: typeof AlbumRoute
  AlbumEventRoute: typeof AlbumEventRoute
  AuthRoute: typeof AuthRoute
  CameraRoute: typeof CameraRoute
  ChallengeDetailRoute: typeof ChallengeDetailRoute
  ChallengesRoute: typeof ChallengesRoute
  DashboardRoute: typeof DashboardRoute
  JoinRoute: typeof JoinRoute
  LobbyRoute: typeof LobbyRoute
  NightRecapRoute: typeof NightRecapRoute
  NotificationsRoute: typeof NotificationsRoute
  PartyRoute: typeof PartyRoute
  ProfileRoute: typeof ProfileRoute
  RecapRoute: typeof RecapRoute
  SabotageRoute: typeof SabotageRoute
  ScanRoute: typeof ScanRoute
  SettingsRoute: typeof SettingsRoute
  ShopRoute: typeof ShopRoute
  VotingRoute: typeof VotingRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/album': {
      id: '/album'
      path: '/album'
      fullPath: '/album'
      preLoaderRoute: typeof AlbumRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/album-event': {
      id: '/album-event'
      path: '/album-event'
      fullPath: '/album-event'
      preLoaderRoute: typeof AlbumEventRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/camera': {
      id: '/camera'
      path: '/camera'
      fullPath: '/camera'
      preLoaderRoute: typeof CameraRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/challenge-detail': {
      id: '/challenge-detail'
      path: '/challenge-detail'
      fullPath: '/challenge-detail'
      preLoaderRoute: typeof ChallengeDetailRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/challenges': {
      id: '/challenges'
      path: '/challenges'
      fullPath: '/challenges'
      preLoaderRoute: typeof ChallengesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/join': {
      id: '/join'
      path: '/join'
      fullPath: '/join'
      preLoaderRoute: typeof JoinRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/lobby': {
      id: '/lobby'
      path: '/lobby'
      fullPath: '/lobby'
      preLoaderRoute: typeof LobbyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/night-recap': {
      id: '/night-recap'
      path: '/night-recap'
      fullPath: '/night-recap'
      preLoaderRoute: typeof NightRecapRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/notifications': {
      id: '/notifications'
      path: '/notifications'
      fullPath: '/notifications'
      preLoaderRoute: typeof NotificationsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/party': {
      id: '/party'
      path: '/party'
      fullPath: '/party'
      preLoaderRoute: typeof PartyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/profile': {
      id: '/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof ProfileRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/recap': {
      id: '/recap'
      path: '/recap'
      fullPath: '/recap'
      preLoaderRoute: typeof RecapRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sabotage': {
      id: '/sabotage'
      path: '/sabotage'
      fullPath: '/sabotage'
      preLoaderRoute: typeof SabotageRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/scan': {
      id: '/scan'
      path: '/scan'
      fullPath: '/scan'
      preLoaderRoute: typeof ScanRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/shop': {
      id: '/shop'
      path: '/shop'
      fullPath: '/shop'
      preLoaderRoute: typeof ShopRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/voting': {
      id: '/voting'
      path: '/voting'
      fullPath: '/voting'
      preLoaderRoute: typeof VotingRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AlbumRoute: AlbumRoute,
  AlbumEventRoute: AlbumEventRoute,
  AuthRoute: AuthRoute,
  CameraRoute: CameraRoute,
  ChallengeDetailRoute: ChallengeDetailRoute,
  ChallengesRoute: ChallengesRoute,
  DashboardRoute: DashboardRoute,
  JoinRoute: JoinRoute,
  LobbyRoute: LobbyRoute,
  NightRecapRoute: NightRecapRoute,
  NotificationsRoute: NotificationsRoute,
  PartyRoute: PartyRoute,
  ProfileRoute: ProfileRoute,
  RecapRoute: RecapRoute,
  SabotageRoute: SabotageRoute,
  ScanRoute: ScanRoute,
  SettingsRoute: SettingsRoute,
  ShopRoute: ShopRoute,
  VotingRoute: VotingRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
